#Code to generate discordant pair plots corresponding to Figure 6 and Supplemental Figure 4
#Input files required: TSV files generated by bash scripts (get_rec_rates.sh) containing recombination count data
#Expected files in working directory: *_Bob2_Car_recombination_counts.tsv, *_Bob2_Bill_recombination_counts.tsv, *_Car_Bill_recombination_counts.tsv, *_Bob2_CCS4_recombination_counts.tsv

library(ggplot2)
library(stringr)
library(dplyr)

setwd("/mnt/d/Research/WhitesonCollab/Data/recombination_rate")

filelist = dir(pattern='Bob2_Car')
bobcardf = read.csv(filelist[1], header=T, sep='\t')
for(i in 2:length(filelist)){
	bobcardf = rbind(bobcardf, read.csv(filelist[i], header=T, sep='\t'))
}

bobcardf$drop = 0
bobcardf$drop[bobcardf$Sample=='S2M'&bobcardf$Time=='5']=1  #We will exclude S2M Time 5 as it is a very strange outlier that might be overstating an the prevalence of an artifact in the alignment.

filelist = dir(pattern='Bob2_Bill')
bobbilldf = read.csv(filelist[1], header=T, sep='\t')
for(i in 2:length(filelist)){
	bobbilldf = rbind(bobbilldf, read.csv(filelist[i], header=T, sep='\t'))
}

bobbilldf$drop = 0
bobbilldf$drop[bobbilldf$Sample=='S2M'&bobbilldf$Time=='5']=1

filelist = dir(pattern='Car_Bill')
carbilldf = read.csv(filelist[1], header=T, sep='\t')
for(i in 2:length(filelist)){
	carbilldf = rbind(carbilldf, read.csv(filelist[i], header=T, sep='\t'))
}

carbilldf$drop = 0
carbilldf$drop[carbilldf$Sample=='S2M'&carbilldf$Time=='5']=1

filelist = dir(pattern='Bob2_CCS4')
bobccs4df = read.csv(filelist[1], header=T, sep='\t')
for(i in 2:length(filelist)){
	bobccs4df = rbind(bobccs4df, read.csv(filelist[i], header=T, sep='\t'))
}

bobcardf$DiscordFreq = bobcardf$DiscordantCount/(bobcardf$TotalReads)
bobbilldf$DiscordFreq = bobbilldf$DiscordantCount/(bobbilldf$TotalReads)
carbilldf$DiscordFreq = carbilldf$DiscordantCount/(carbilldf$TotalReads)
bobccs4df$DiscordFreq = bobccs4df$DiscordantCount/(bobccs4df$TotalReads)

bobcardf$pair = 'Bob-Car'
bobbilldf$pair = 'Bob-Bill'
carbilldf$pair = 'Car-Bill'
bobccs4df$pair = 'Bob-CCS4'

columnset = c('pair','Sample','Time','SplitCount','DiscordantCount','TotalReads','DiscordFreq')
allrecdf = rbind(bobcardf[,columnset], bobbilldf[,columnset])
allrecdf = rbind(allrecdf, carbilldf[,columnset])
allrecdf = rbind(allrecdf, bobccs4df[,columnset])

#Drop S2M at t5
allrecdf$drop = 0
allrecdf$drop[allrecdf$Sample=='S2M' & allrecdf$Time == 5] = 1
allrecdf = subset(allrecdf, drop==0)

#Fix cousin T20 names (artifact of how the files were originally set up locally)
allrecdf$Sample = str_replace(allrecdf$Sample, '_T20', '')
allrecdf = allrecdf[-which(is.na(allrecdf$DiscordFreq)),]  #some values are NA if there were no events. E.g. Bob-CCS4 at Time 20

#Exclude the ancestors from the summary plot
#Update Sample labels for manuscript nomenclature
allrecdf$Sample = str_replace(allrecdf$Sample, 'Sisters', 'Similar')
allrecdf$Sample = str_replace(allrecdf$Sample, 'Cousins', 'Dissimilar')
allrecdf$Sample = str_replace(allrecdf$Sample, 'C', 'D')
allrecdf$Sample = str_replace(allrecdf$Sample, 'I', 'P')
allrecdf$Sample = factor(allrecdf$Sample, levels = c('Phage_Similar_R1','Phage_Similar_R2','Phage_Similar_R3',
													 'Phage_Dissimilar_R1','Phage_Dissimilar_R2','Phage_Dissimilar_R3',
													 'S1M','S2M','S3M','S1P','S2P','S3P',
													 'D1M','D2M','D3M','D1P','D2P','D3P'))
colrange = brewer.pal(9, 'Set1')
col_fun = c(
	'Phage_Similar_R1' = colrange[9],
	'Phage_Similar_R2' = colrange[9],
	'Phage_Similar_R3' = colrange[9],
	'Phage_Dissimilar_R1' = colrange[9],
	'Phage_Dissimilar_R2' = colrange[9],
	'Phage_Dissimilar_R3' = colrange[9],
	'S1M' = colrange[1],
	'S2M' = colrange[2],
	'S3M' = colrange[3],
	'S1P' = colrange[4],
	'S2P' = colrange[5],
	'S3P' = colrange[7],
	'D1M' = colrange[1],
	'D2M' = colrange[2],
	'D3M' = colrange[3],
	'D1P' = colrange[4],
	'D2P' = colrange[5],
	'D3P' = colrange[7]
)

col_fun_alt = c(
	'Similar_t0' = colrange[9],
	'Dissimilar_t0' = colrange[9],
	'S1M' = colrange[1],
	'S2M' = colrange[2],
	'S3M' = colrange[3],
	'S1P' = colrange[4],
	'S2P' = colrange[5],
	'S3P' = colrange[7],
	'D1M' = colrange[1],
	'D2M' = colrange[2],
	'D3M' = colrange[3],
	'D1P' = colrange[4],
	'D2P' = colrange[5],
	'D3P' = colrange[7]
)
#counts for supplement. Frequencies for main text

#Set the sample ID for the t0 to just "t0"
allrecdf$SampleAlt = as.character(allrecdf$Sample)
allrecdf$SampleAlt = str_replace(allrecdf$SampleAlt, 'Phage_Similar_R[123]', 'Similar_t0')
allrecdf$SampleAlt = str_replace(allrecdf$SampleAlt, 'Phage_Dissimilar_R[123]', 'Dissimilar_t0')
allrecdf$SampleAlt = factor(allrecdf$SampleAlt, levels = c('Similar_t0','Dissimilar_t0','S1M','S2M','S3M','S1P','S2P','S3P','D1M','D2M','D3M','D1P','D2P','D3P'))

disc_plot_sibs_count = ggplot(subset(allrecdf, pair!='Bob-CCS4' & Time!='ancestor'), aes(x=as.numeric(Time), y=DiscordantCount, color=SampleAlt)) +
	facet_wrap(vars(pair), scales='free')+
	geom_line()+
	geom_point()+
	xlab('Cycle')+
	ylab('Total Discordant Pairs')+
	labs(color = 'Sample')+
	guides(color = guide_legend(nrow = 3))+
	scale_color_manual(values = col_fun_alt, breaks = c('S1M','S2M','S3M','S1P','S2P','S3P','Similar_t0'))+
	xlab('Time')+
	theme_bw() + theme(text = element_text(face='bold', size=8), legend.position = 'bottom')

disc_plot_sibs_freq = ggplot(subset(allrecdf, pair!='Bob-CCS4' & Time!='ancestor'), aes(x=as.numeric(Time), y=DiscordFreq, color=SampleAlt)) +
	facet_wrap(vars(pair), scales='free')+
	geom_line()+
	geom_point()+
	xlab('Cycle')+
	ylab('Total Discordant Pairs')+
	labs(color = 'Sample')+
	guides(color = guide_legend(nrow = 3))+
	scale_color_manual(values = col_fun_alt, breaks = c('S1M','S2M','S3M','S1P','S2P','S3P','Similar_t0'))+
	xlab('Time')+
	theme_bw()+ theme(text = element_text(face='bold', size=8), legend.position = 'bottom')
	
disc_plot_cousins_count = ggplot(subset(allrecdf, pair=='Bob-CCS4' & Time!='ancestor'), aes(x=as.numeric(Time), y=DiscordantCount, color=SampleAlt)) +
	facet_wrap(vars(pair))+
	geom_line()+
	geom_point()+
	xlab('Cycle')+
	ylab('Total Discordant Pairs')+
	labs(color = 'Sample')+
	guides(color = guide_legend(nrow = 3))+
	scale_color_manual(values = col_fun_alt, breaks = c('D1M','D2M','D3M','D1P','D2P','D3P','Dissimilar_t0'))+
	xlab('Time')+
	theme_bw()+ theme(text = element_text(face='bold', size=8), legend.position = 'bottom')

disc_plot_cousins_freq = ggplot(subset(allrecdf, pair=='Bob-CCS4' & Time!='ancestor'), aes(x=as.numeric(Time), y=DiscordFreq, color=SampleAlt)) +
	facet_wrap(vars(pair))+
	geom_line()+
	geom_point()+
	xlab('Cycle')+
	ylab('Total Discordant Pairs')+
	labs(color = 'Sample')+
	guides(color = guide_legend(nrow = 3))+
	scale_color_manual(values = col_fun_alt, breaks = c('D1M','D2M','D3M','D1P','D2P','D3P','Dissimilar_t0'))+
	xlab('Time')+
	theme_bw()+ theme(text = element_text(face='bold', size=8), legend.position = 'bottom')

#Save plots
png('../discord_freq_sim.png', height=400, width=800)
print(disc_plot_sibs_freq)
dev.off()

png('../discord_count_sim.png', height=400, width=800)
print(disc_plot_sibs_count)
dev.off()

png('../discord_freq_diss.png', height=500, width=400)
print(disc_plot_cousins_freq)
dev.off()

png('../discord_count_diss.png', height=500, width=400)
print(disc_plot_cousins_count)
dev.off()

pdf('../discord_freq_sim.pdf', height=4, width=4.5)
print(disc_plot_sibs_freq)
dev.off()

pdf('../discord_count_sim.pdf', height=4, width=4.5)
print(disc_plot_sibs_count)
dev.off()

pdf('../discord_freq_diss.pdf', height=5, width=3.25)
print(disc_plot_cousins_freq + theme(plot.margin = margin(5,15,5,5, 'mm')))
dev.off()

pdf('../discord_count_diss.pdf', height=5, width=3.25)
print(disc_plot_cousins_count + theme(plot.margin = margin(5,15,5,5, 'mm')))
dev.off()

## Replot without legends and with dissimilar smaller ##
disc_plot_sibs_freq2 = ggplot(subset(allrecdf, pair!='Bob-CCS4' & Time!='ancestor'), aes(x=as.numeric(Time), y=DiscordFreq, color=SampleAlt)) +
	facet_wrap(vars(pair))+
	geom_line()+
	geom_point()+
	xlab('Cycle')+
	ylab('Discordant Pairs Frequency')+
	scale_color_manual(values = col_fun_alt, breaks = c('S1M','S2M','S3M','S1P','S2P','S3P','Similar_t0'))+
	xlab('Time')+
	theme_bw()+ theme(text = element_text(face='bold', size=8), legend.position = 'none')
	
	
disc_plot_cousins_freq2 = ggplot(subset(allrecdf, pair=='Bob-CCS4' & Time!='ancestor'), aes(x=as.numeric(Time), y=DiscordFreq, color=SampleAlt)) +
	facet_wrap(vars(pair))+
	geom_line()+
	geom_point()+
	xlab('Cycle')+
	ylab('Discordant Pairs Frequency')+
	scale_color_manual(values = col_fun_alt, breaks = c('D1M','D2M','D3M','D1P','D2P','D3P','Dissimilar_t0'))+
	xlab('Time')+
	theme_bw()+ theme(text = element_text(face='bold', size=8), legend.position = 'none')

pdf('../discord_freq_sim_noLegend.pdf', height=4, width=4.5)
print(disc_plot_sibs_freq2)
dev.off()

pdf('../discord_freq_diss_noLegend.pdf', height=4, width=2)
print(disc_plot_cousins_freq2)
dev.off()

#Plot discordant locations
samplelist = c('S1M','S2M','S3M','S1I','S2I','S3I')
timelist = paste0('t',c(1,2,3,4,5,10,15,20))
samplelist2 = c('C1M','C2M','C3M','C1I','C2I','C3I')

setwd("/mnt/d/Research/WhitesonCollab/Data/RawReads/sisters_t1")

#Note: the files are longer than some previous steps and the for loops below will be a bit slow.
rec.df = read.table(paste0(samplelist[1],"_Bob2_Car_recombinant_discordant_depth.txt")) %>% mutate(sample=samplelist[1], time = 't1')
for(i in 2:length(samplelist)){
	temp = read.table(paste0(samplelist[i],"_Bob2_Car_recombinant_discordant_depth.txt")) %>% mutate(sample=samplelist[i], time = 't1')
	rec.df = rbind(rec.df, temp)
}
for(i in 2:length(timelist)){
	setwd(paste0("../sisters_",timelist[i]))
	for(j in 1:length(samplelist)){
		temp = read.table(paste0(samplelist[j],"_Bob2_Car_recombinant_discordant_depth.txt")) %>% mutate(sample=samplelist[j], time = timelist[i])
	rec.df = rbind(rec.df, temp)
	}
}

colnames(rec.df)[1:3] = c('contig','position','depth')
rec.df$ID = paste0(rec.df$sample, '_', rec.df$time)
idorder = character()
for(i in 1:length(samplelist)){for(j in 1:length(timelist)){
idorder = c(idorder, paste0(samplelist[i],'_',timelist[j]))}}
rec.df$ID = factor(rec.df$ID, levels=idorder)
rec.df$sample = factor(rec.df$sample, levels=samplelist)
rec.df$time = factor(rec.df$time, levels = timelist)

rec.df$RelDepth = 0
for(i in 1:length(samplelist)){
	for(j in 1:length(timelist)){
		temp = which(rec.df$sample == samplelist[i] & rec.df$time == timelist[j])
		rec.df$RelDepth[temp] = rec.df$depth[temp]/max(rec.df$depth[temp])
	}
}

#Prior to plotting, we need to re-orient the positions to match the layout in other manuscript figures, which begins from the terminase genes. We follow the same steps as used in mutation_plots.txt. #These steps assume that mutation_plots has been run and the objects tempgtf_bob, newgtf_car, and tempgtf_ccs4 are still available in the workspace, as well as nbob, ncar, and nccs4.
bobdf = subset(rec.df, contig == 'Bob2')
cardf = subset(rec.df, contig == 'Car')

#Bob
termgene = grep('terminase', tempgtf_bob$product)[1]
termstart = tempgtf_bob$start[termgene]
bobdf$NewPosition = 0
bobdf$NewPosition[bobdf$position >= termstart] = bobdf$position[bobdf$position >= termstart] - termstart + 1
bobdf$NewPosition[bobdf$position < termstart] = nbob - (termstart - bobdf$position[bobdf$position < termstart])

#Car
cardf$NewPosition = ncar - cardf$position + 1 #This should reverse the values to match the first step in newgtf_car
termgene = grep('terminase', newgtf_car$product)[1]
termstart = newgtf_car$start2[termgene]  #use start2 to match the reversed start values
cardf$NewPosition2 = 0
cardf$NewPosition2[cardf$NewPosition >= termstart] = cardf$NewPosition[cardf$NewPosition >= termstart] - termstart + 1
cardf$NewPosition2[cardf$NewPosition < termstart] = ncar - (termstart - cardf$NewPosition[cardf$NewPosition < termstart])
cardf$NewPosition = cardf$NewPosition2 #update so that we can have the same columns when rbind-ing each df back to rec.df

rec.df = rbind(bobdf, cardf[,colnames(bobdf)])
rec.df$sample = as.character(rec.df$sample)
rec.df$sample = str_replace(rec.df$sample, 'I', 'P')
rec.df$sample = factor(rec.df$sample, levels = c('S1M','S2M','S3M','S1P','S2P','S3P'))
rec_pos_sibs_bob = ggplot(subset(rec.df, contig=='Bob2'), aes(x=NewPosition, y=time, color=log10(depth), alpha=depth, size=depth))+
	facet_wrap(vars(sample), ncol=1, strip.position = 'right')+
	geom_point()+
	ylab('Cycle')+
	xlab('Position')+
	scale_color_gradient2(low='white', mid='darkblue', high='red', midpoint=1)+
	scale_alpha_continuous(range=c(0,1))+
	scale_size_continuous(range=c(0,2))+
	theme_bw()+theme(text=element_text(size=8))

rec_pos_sibs_car = ggplot(subset(rec.df, contig=='Car'), aes(x=NewPosition, y=time, color=log10(depth), alpha=depth, size=depth))+
	facet_wrap(vars(sample), ncol=1, strip.position = 'right')+
	geom_point()+
	ylab('Cycle')+
	xlab('Position')+
	scale_color_gradient2(low='white', mid='darkblue', high='red', midpoint=1)+
	scale_alpha_continuous(range=c(0,1))+
	scale_size_continuous(range=c(0,2))+
	theme_bw()+theme(text=element_text(size=8))

pdf('../../discordant_positions_sim_bob_narrow.pdf', height=5.5, width=3.75)
print(rec_pos_sibs_bob)
dev.off()

pdf('../../discordant_positions_sim_car_narrow.pdf', height=5.5, width=3.75)
print(rec_pos_sibs_car)
dev.off()

#replot raster
library(ggrastr)
rec_pos_sibs_bob_rast = ggplot(subset(rec.df, contig=='Bob2'), aes(x=NewPosition, y=time, color=log10(depth), alpha=depth, size=depth))+
	facet_wrap(vars(sample), ncol=1, strip.position = 'right')+
	geom_point_rast()+
	ylab('Cycle')+
	xlab('Position')+
	scale_color_gradient2(low='white', mid='darkblue', high='red', midpoint=1)+
	scale_alpha_continuous(range=c(0,1))+
	scale_size_continuous(range=c(0,2))+
	theme_bw()+theme(text=element_text(size=8))

rec_pos_sibs_car_rast = ggplot(subset(rec.df, contig=='Car'), aes(x=NewPosition, y=time, color=log10(depth), alpha=depth, size=depth))+
	facet_wrap(vars(sample), ncol=1, strip.position = 'right')+
	geom_point_rast()+
	ylab('Cycle')+
	xlab('Position')+
	scale_color_gradient2(low='white', mid='darkblue', high='red', midpoint=1)+
	scale_alpha_continuous(range=c(0,1))+
	scale_size_continuous(range=c(0,2))+
	theme_bw()+theme(text=element_text(size=8))

pdf('../../discordant_positions_sim_bob_narrow_raster.pdf', height=5.5, width=3.75)
print(rec_pos_sibs_bob_rast)
dev.off()

pdf('../../discordant_positions_sim_car_narrow_raster.pdf', height=5.5, width=3.75)
print(rec_pos_sibs_car_rast)
dev.off()


#Plots for cousins
samplelist2 = c('C1M','C2M','C3M','C1I','C2I','C3I')
setwd("../cousins_t1")
rec.df.cousins = read.table(paste0(samplelist2[1],"_Bob2_CCS4_recombinant_discordant_depth.txt")) %>% mutate(sample=samplelist2[1], time = 't1')
for(i in 2:length(samplelist2)){
	temp = read.table(paste0(samplelist2[i],"_Bob2_CCS4_recombinant_discordant_depth.txt")) %>% mutate(sample=samplelist2[i], time = 't1')
	rec.df.cousins = rbind(rec.df.cousins, temp)
}

for(i in 2:length(timelist[-8])){
	setwd(paste0("../cousins_",timelist[i]))
	for(j in 1:length(samplelist2)){
		temp = readLines(paste0(samplelist2[j],"_Bob2_CCS4_recombinant_discordant_depth.txt"))
		if(length(temp) > 0){
			temp = read.table(paste0(samplelist2[j],"_Bob2_CCS4_recombinant_discordant_depth.txt")) %>% mutate(sample=samplelist2[j], time = timelist[i])
			rec.df.cousins = rbind(rec.df.cousins, temp)
		}
	}
}

#change for T20
setwd("../cousins_t20")
for(j in 1:length(samplelist2)){
	temp = readLines(paste0(samplelist2[j],"_T20_Bob2_CCS4_recombinant_discordant_depth.txt"))
	if(length(temp) > 0){
		temp = read.table(paste0(samplelist2[j],"_T20_Bob2_CCS4_recombinant_discordant_depth.txt")) %>% mutate(sample=samplelist2[j], time = timelist[8])
		rec.df.cousins = rbind(rec.df.cousins, temp)
	}
}

colnames(rec.df.cousins)[1:3] = c('contig','position','depth')
rec.df.cousins$ID = paste0(rec.df.cousins$sample, '_', rec.df.cousins$time)
idorder = character()
for(i in 1:length(samplelist2)){for(j in 1:length(timelist)){
	idorder = c(idorder, paste0(samplelist2[i],'_',timelist[j]))}
}
rec.df.cousins$ID = factor(rec.df.cousins$ID, levels=idorder)
rec.df.cousins$sample = factor(rec.df.cousins$sample, levels=samplelist2)
rec.df.cousins$time = factor(rec.df.cousins$time, levels = timelist)

rec.df.cousins$RelDepth = 0
for(i in 1:length(samplelist2)){
	for(j in 1:length(timelist)){
		temp = which(rec.df.cousins$sample == samplelist2[i] & rec.df.cousins$time == timelist[j])
		rec.df.cousins$RelDepth[temp] = rec.df.cousins$depth[temp]/max(rec.df.cousins$depth[temp])
	}
}

#Update positions as done above for siblings. (Repeats the update for Bob)
bobdf = subset(rec.df.cousins, contig == 'Bob2')
ccs4df = subset(rec.df.cousins, contig == 'CCS4')

#Bob
termgene = grep('terminase', tempgtf_bob$product)[1]
termstart = tempgtf_bob$start[termgene]
bobdf$NewPosition = 0
bobdf$NewPosition[bobdf$position >= termstart] = bobdf$position[bobdf$position >= termstart] - termstart + 1
bobdf$NewPosition[bobdf$position < termstart] = nbob - (termstart - bobdf$position[bobdf$position < termstart])

#CCS4
termgene = grep('terminase', tempgtf_ccs4$product)[1]
termstart = tempgtf_ccs4 $start[termgene]
ccs4df$NewPosition = 0
ccs4df$NewPosition[ccs4df$position >= termstart] = ccs4df$position[ccs4df$position >= termstart] - termstart + 1
ccs4df$NewPosition[ccs4df$position < termstart] = nccs4 - (termstart - ccs4df$position[ccs4df$position < termstart])

rec.df.cousins = rbind(bobdf, ccs4df)

#Also update labels for the manuscript
rec.df.cousins$sample = as.character(rec.df.cousins$sample)
rec.df.cousins$sample = str_replace(rec.df.cousins$sample, 'C', 'D')
rec.df.cousins$sample = str_replace(rec.df.cousins$sample, 'I', 'P')
rec.df.cousins$sample = factor(rec.df.cousins$sample, levels = c('D1M','D2M','D3M','D1P','D2P','D3P'))

rec_pos_cousins_bob = ggplot(subset(rec.df.cousins, contig=='Bob2'), aes(x=NewPosition, y=time, color=depth, alpha=depth, size=depth))+
	facet_wrap(vars(sample), ncol=1, strip.position = 'right')+
	geom_point()+
	ylab('Cycle')+
	xlab('Position')+
	scale_color_gradient2(low='white', mid='darkblue', high='red', midpoint=1)+
	scale_alpha_continuous(range=c(0,1))+
	scale_size_continuous(range=c(0,2))+
	theme_bw()+theme(text=element_text(size=8))

rec_pos_cousins_ccs4 = ggplot(subset(rec.df.cousins, contig=='CCS4'), aes(x=NewPosition, y=time, color=depth, alpha=depth, size=depth))+
	facet_wrap(vars(sample), ncol=1, strip.position = 'right')+
	geom_point()+
	ylab('Cycle')+
	xlab('Position')+
	scale_color_gradient2(low='white', mid='darkblue', high='red', midpoint=1)+
	scale_alpha_continuous(range=c(0,1))+
	scale_size_continuous(range=c(0,2))+
	theme_bw()+theme(text=element_text(size=8))

pdf('../../discordant_positions_dis_bob_narrow.pdf', height=5.5, width=3.75)
print(rec_pos_cousins_bob)
dev.off()

pdf('../../discordant_positions_dis_ccs4_narrow.pdf', height=5.5, width=3.75)
print(rec_pos_cousins_ccs4)
dev.off()

#replot raster

rec_pos_cousins_bob_rast = ggplot(subset(rec.df.cousins, contig=='Bob2'), aes(x=NewPosition, y=time, color=depth, alpha=depth, size=depth))+
	facet_wrap(vars(sample), ncol=1, strip.position = 'right')+
	geom_point_rast()+
	ylab('Cycle')+
	xlab('Position')+
	scale_color_gradient2(low='white', mid='darkblue', high='red', midpoint=1)+
	scale_alpha_continuous(range=c(0,1))+
	scale_size_continuous(range=c(0,2))+
	theme_bw()+theme(text=element_text(size=8))

rec_pos_cousins_ccs4_rast = ggplot(subset(rec.df.cousins, contig=='CCS4'), aes(x=NewPosition, y=time, color=depth, alpha=depth, size=depth))+
	facet_wrap(vars(sample), ncol=1, strip.position = 'right')+
	geom_point_rast()+
	ylab('Cycle')+
	xlab('Position')+
	scale_color_gradient2(low='white', mid='darkblue', high='red', midpoint=1)+
	scale_alpha_continuous(range=c(0,1))+
	scale_size_continuous(range=c(0,2))+
	theme_bw()+theme(text=element_text(size=8))

pdf('../../discordant_positions_dis_bob_narrow_raster.pdf', height=5.5, width=3.75)
print(rec_pos_cousins_bob_rast)
dev.off()

pdf('../../discordant_positions_dis_ccs4_narrow_raster.pdf', height=5.5, width=3.75)
print(rec_pos_cousins_ccs4_rast)
dev.off()

# Aligning discordant pairs to their respective genome maps (Figure 6C)
netplot <- function(pair_coords, ref1, ref2, gtf1=tempgtf_bob, gtf2=newgtf_car, n1=nbob, n2=ncar, reorder = TRUE){
	colnames(pair_coords) = c('y_start','x_start','y_end','x_end')
	
	# if reorder == TRUE, need to correct the positions using the provided gtfs. Note: only set up for Bob and Car
	if(reorder == TRUE){
		termgene1 = grep('terminase', gtf1$product)[1]
		termstart1 = gtf1$start[termgene1]
		pair_coords$new_x_start = 0
		pair_coords$new_x_start[pair_coords$x_start >= termstart1] = pair_coords$x_start[pair_coords$x_start >= termstart1] - termstart1 + 1
		pair_coords$new_x_start[pair_coords$x_start < termstart1] = n1 - (termstart1 - pair_coords$x_start[pair_coords$x_start < termstart1])

		pair_coords$new_x_end = n2 - pair_coords$x_end + 1 #This should reverse the values to match the first step in newgtf_car
		termgene2 = grep('terminase', gtf2$product)[1]
		termstart2 = gtf2$start2[termgene2]  #use start2 to match the reversed start values
		pair_coords$new_x_end2 = 0
		pair_coords$new_x_end2[pair_coords$new_x_end >= termstart2] = pair_coords$new_x_end[pair_coords$new_x_end >= termstart2] - termstart2 + 1
		pair_coords$new_x_end2[pair_coords$new_x_end < termstart2] = n2 - (termstart2 - pair_coords$new_x_end[pair_coords$new_x_end < termstart2])
		
		#finally, reset the original positions to the new values so the plot is always the same setup
		pair_coords$x_start = pair_coords$new_x_start
		pair_coords$x_end = pair_coords$new_x_end2
	}		
	
	results = list()
	results$pair_coords = pair_coords
	results$plot = ggplot(pair_coords, aes(x=x_start, y=y_start, xend=x_end, yend=y_end))+
		geom_segment(linewidth = 0.1, alpha = 0.1)+
		scale_y_discrete(limits = c(ref2, ref1))+
		theme_bw()
	return(results)
}

# Build one plot for each Similar phage replicate at t20
setwd("../sisters_t20")
nplot_s1m = netplot(read.table("S1M_Bob2_Car_discordant_pairs_table.txt"), 'Bob2','Car')
pdf('../../t20_bob_car_s1m_align.pdf', height=6, width=8)
(genome_bob+unpad)/plot_spacer()/(nplot_s1m$plot+theme_void()+unpad)/plot_spacer()/(genome_car+unpad) + plot_layout(heights = c(4, -1, 1, -1, 4))
dev.off()

nplot_s2m = netplot(read.table("S2M_Bob2_Car_discordant_pairs_table.txt"), 'Bob2','Car')
pdf('../../t20_bob_car_s2m_align.pdf', height=6, width=8)
(genome_bob+unpad)/plot_spacer()/(nplot_s2m$plot+theme_void()+unpad)/plot_spacer()/(genome_car+unpad) + plot_layout(heights = c(4, -1, 1, -1, 4))
dev.off()

nplot_s3m = netplot(read.table("S3M_Bob2_Car_discordant_pairs_table.txt"), 'Bob2','Car')
pdf('../../t20_bob_car_s3m_align.pdf', height=6, width=8)
(genome_bob+unpad)/plot_spacer()/(nplot_s3m$plot+theme_void()+unpad)/plot_spacer()/(genome_car+unpad) + plot_layout(heights = c(4, -1, 1, -1, 4))
dev.off()

nplot_s1p = netplot(read.table("S1I_Bob2_Car_discordant_pairs_table.txt"), 'Bob2','Car')
pdf('../../t20_bob_car_s1p_align.pdf', height=6, width=8)
(genome_bob+unpad)/plot_spacer()/(nplot_s1p$plot+theme_void()+unpad)/plot_spacer()/(genome_car+unpad) + plot_layout(heights = c(4, -1, 1, -1, 4))
dev.off()

nplot_s2p = netplot(read.table("S2I_Bob2_Car_discordant_pairs_table.txt"), 'Bob2','Car')
pdf('../../t20_bob_car_s2p_align.pdf', height=6, width=8)
(genome_bob+unpad)/plot_spacer()/(nplot_s2p$plot+theme_void()+unpad)/plot_spacer()/(genome_car+unpad) + plot_layout(heights = c(4, -1, 1, -1, 4))
dev.off()

nplot_s3p = netplot(read.table("S3I_Bob2_Car_discordant_pairs_table.txt"), 'Bob2','Car')
pdf('../../t20_bob_car_s3p_align.pdf', height=6, width=8)
(genome_bob+unpad)/plot_spacer()/(nplot_s3p$plot+theme_void()+unpad)/plot_spacer()/(genome_car+unpad) + plot_layout(heights = c(4, -1, 1, -1, 4))
dev.off()

